/* Generated by Babel */
/*------------------------------------------------------------------------------------------
| Global Variables
--------------------------------------------------------------------------------------------*/

'use strict';

var player1 = null;
var allFightersInTable = Array.from(document.querySelectorAll('#fighter-select table tr td'));
var fighterpics = document.querySelector('#fighter-pics');

/*------------------------------------------------------------------------------------------
| Eventhandler
--------------------------------------------------------------------------------------------*/

document.querySelector('#create-fighter').addEventListener('click', function () {
    player1 = new Fighter(document.querySelector('#fighterName').value);
    player1.updateList();
});

document.querySelector('#fight').addEventListener('click', function () {
    var arena = new Ring();

    if (typeof player1 == null) {
        console.log("Create a player first:");
    } else {
        arena.battle(player1, new Fighter('dummy'));
    }
});

allFightersInTable.forEach(function (element) {
    element.addEventListener('click', function () {
        player1 = createFighter(element.id);
        showOfSecondPlayer();
        document.querySelector('#fighter-select').classList.add('hidden');
        document.querySelector('#battle-stats').classList.remove('hidden');
    });

    element.addEventListener('mouseover', function () {
        fighterpics.children[0].setAttribute("src", element.children[0].getAttribute('src'));
    });
});

document.querySelector('#story-mode').addEventListener('click', function () {
    document.querySelector('#player-select-menu').classList.remove('hidden');
    console.log('Try to show the playerselect screen.');
    document.querySelector('#modes').classList.add('hidden');
});

var showOfSecondPlayer = function showOfSecondPlayer() {
    console.log("this one is your opponent fighter-" + Math.round(Math.random() * allFightersInTable.length));
    document.querySelector("#fighter-" + Math.round(Math.random() * allFightersInTable.length)).classList.add('blueBorder');
};